"""add two_factor_enabled to users

Revision ID: 2c96db3cb6a7
Revises: 47ad80e964ed
Create Date: 2026-08-09 07:30:15.267490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2c96db3cb6a7'
down_revision: Union[str, None] = '47ad80e964ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('two_factor_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'two_factor_enabled')
    # ### end Alembic commands ###
