"""add join_requests table

Revision ID: 47ad80e964ed
Revises: 582f1cfbcd55
Create Date: 2026-08-07 22:57:26.174911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '47ad80e964ed'
down_revision: Union[str, None] = '582f1cfbcd55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('join_requests',
    sa.Column('community_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_join_requests_community_id'), 'join_requests', ['community_id'], unique=False)
    op.create_index(op.f('ix_join_requests_user_id'), 'join_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_join_requests_user_id'), table_name='join_requests')
    op.drop_index(op.f('ix_join_requests_community_id'), table_name='join_requests')
    op.drop_table('join_requests')
    # ### end Alembic commands ###
