"""add stream_key to communities

Revision ID: 605a5c30ef72
Revises: 7d7a113fd62c
Create Date: 2026-08-02 19:25:02.814449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '605a5c30ef72'
down_revision: Union[str, None] = '7d7a113fd62c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add as NOT NULL with a server_default so existing rows get a random key
    # (adding a NOT NULL column without a default would fail on a non-empty table).
    op.add_column(
        'communities',
        sa.Column(
            'stream_key',
            sa.String(length=64),
            nullable=False,
            server_default=sa.text("'sk_' || md5(random()::text || clock_timestamp()::text)"),
        ),
    )
    op.create_index(op.f('ix_communities_stream_key'), 'communities', ['stream_key'], unique=True)
    # New rows use the model's Python default; drop the backfill server_default.
    op.alter_column('communities', 'stream_key', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_communities_stream_key'), table_name='communities')
    op.drop_column('communities', 'stream_key')
    # ### end Alembic commands ###
