"""add user is_active and community is_suspended

Revision ID: afd52cc0f7c1
Revises: 605a5c30ef72
Create Date: 2026-08-04 21:49:40.102162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'afd52cc0f7c1'
down_revision: Union[str, None] = '605a5c30ef72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default backfills existing rows (true / false), then dropped so
    # the model's Python default is used for new inserts.
    op.add_column('communities', sa.Column('is_suspended', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.alter_column('communities', 'is_suspended', server_default=None)
    op.alter_column('users', 'is_active', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('communities', 'is_suspended')
    # ### end Alembic commands ###
