"""replace is_admin with system_role enum

Revision ID: fde5b87d1a01
Revises: 2c96db3cb6a7
Create Date: 2026-08-09 07:56:34.381127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fde5b87d1a01'
down_revision: Union[str, None] = '2c96db3cb6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add system_role (default 'user'), migrate existing is_admin=true → 'admin',
    # then drop is_admin.
    op.add_column('users', sa.Column('system_role', sa.String(length=20), server_default=sa.text("'user'"), nullable=False))
    op.execute("UPDATE users SET system_role = 'admin' WHERE is_admin = true")
    op.drop_column('users', 'is_admin')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'system_role')
    # ### end Alembic commands ###
