/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthedRouteImport } from "./routes/_authed";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as RegisterRouteImport } from "./routes/register";
import { Route as AuthedAdminRouteImport } from "./routes/_authed/admin";
import { Route as AuthedHomeRouteImport } from "./routes/_authed/home";
import { Route as AuthedCommunityIdRouteImport } from "./routes/_authed/community.$id";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedRoute = AuthedRouteImport.update({
  id: "/_authed",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedHomeRoute = AuthedHomeRouteImport.update({
  id: "/home",
  path: "/home",
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedCommunityIdRoute = AuthedCommunityIdRouteImport.update({
  id: "/community/$id",
  path: "/community/$id",
  getParentRoute: () => AuthedRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/admin": typeof AuthedAdminRoute;
  "/home": typeof AuthedHomeRoute;
  "/community/$id": typeof AuthedCommunityIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/admin": typeof AuthedAdminRoute;
  "/home": typeof AuthedHomeRoute;
  "/community/$id": typeof AuthedCommunityIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_authed": typeof AuthedRouteWithChildren;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/_authed/admin": typeof AuthedAdminRoute;
  "/_authed/home": typeof AuthedHomeRoute;
  "/_authed/community/$id": typeof AuthedCommunityIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/login" | "/register" | "/admin" | "/home" | "/community/$id";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/login" | "/register" | "/admin" | "/home" | "/community/$id";
  id:
    | "__root__"
    | "/"
    | "/_authed"
    | "/login"
    | "/register"
    | "/_authed/admin"
    | "/_authed/home"
    | "/_authed/community/$id";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthedRoute: typeof AuthedRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  RegisterRoute: typeof RegisterRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authed": {
      id: "/_authed";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/register": {
      id: "/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof RegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authed/admin": {
      id: "/_authed/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AuthedAdminRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/home": {
      id: "/_authed/home";
      path: "/home";
      fullPath: "/home";
      preLoaderRoute: typeof AuthedHomeRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/community/$id": {
      id: "/_authed/community/$id";
      path: "/community/$id";
      fullPath: "/community/$id";
      preLoaderRoute: typeof AuthedCommunityIdRouteImport;
      parentRoute: typeof AuthedRoute;
    };
  }
}

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRoute;
  AuthedHomeRoute: typeof AuthedHomeRoute;
  AuthedCommunityIdRoute: typeof AuthedCommunityIdRoute;
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRoute,
  AuthedHomeRoute: AuthedHomeRoute,
  AuthedCommunityIdRoute: AuthedCommunityIdRoute,
};

const AuthedRouteWithChildren = AuthedRoute._addFileChildren(AuthedRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
