#!/bin/sh
# ─────────────────────────────────────────────────────────────────────
# adda — one-command installer
#
#   curl -fsSL <your-release-url>/install.sh | sh
#   (or clone the repo and run: ./install.sh)
#
# Asks for a domain and an admin email. Generates every secret,
# writes .env, starts the stack with automatic HTTPS, and prints the
# admin password exactly once.
# ─────────────────────────────────────────────────────────────────────
set -eu

REPO_DIR="$(cd "$(dirname "$0")/.." 2>/dev/null && pwd || pwd)"
ENV_FILE="$REPO_DIR/.env"

say()  { printf '\033[1;33madda\033[0m %s\n' "$1"; }
die()  { printf '\033[1;31merror:\033[0m %s\n' "$1" >&2; exit 1; }

# ── prerequisites ───────────────────────────────────────────────────
command -v docker >/dev/null 2>&1 || die "docker is required: https://docs.docker.com/engine/install/"
docker compose version >/dev/null 2>&1 || die "docker compose v2 is required (docker-compose v1 is not supported)"
command -v openssl >/dev/null 2>&1 || die "openssl is required (usually preinstalled)"

# ── gather answers (env vars win, so CI/unattended installs work) ──
ADDA_DOMAIN="${ADDA_DOMAIN:-}"
SUPERADMIN_EMAIL="${SUPERADMIN_EMAIL:-}"

if [ -z "$ADDA_DOMAIN" ]; then
	printf 'Domain your adda will live on (e.g. adda.example.com): '
	read -r ADDA_DOMAIN
fi
[ -n "$ADDA_DOMAIN" ] || die "a domain is required (point its DNS A record at this server first)"

case "$ADDA_DOMAIN" in
localhost | 127.0.0.1)
	die "use a real domain for installs — for local development run: docker compose -f compose.yaml -f compose.dev.yaml up"
	;;
esac

if [ -z "$SUPERADMIN_EMAIL" ]; then
	printf 'Admin email (also used for HTTPS certificate notices) [%s]: ' "admin@$ADDA_DOMAIN"
	read -r SUPERADMIN_EMAIL
	SUPERADMIN_EMAIL="${SUPERADMIN_EMAIL:-admin@$ADDA_DOMAIN}"
fi

# ── optional SMTP (skip now, add later in .env + restart) ───────────
SMTP_HOST="${SMTP_HOST:-}"
if [ -z "$SMTP_HOST" ] && [ -z "${NONINTERACTIVE:-}" ]; then
	printf 'Set up email now (password-reset / notification mail)? [y/N]: '
	read -r setup_smtp
	case "$setup_smtp" in
	y | Y)
		printf 'SMTP host (e.g. smtp.fastmail.com): '
		read -r SMTP_HOST
		[ -n "$SMTP_HOST" ] || die "SMTP host cannot be empty if enabling email"
		printf 'SMTP port [587]: '
		read -r SMTP_PORT
		SMTP_PORT="${SMTP_PORT:-587}"
		printf 'SMTP username: '
		read -r SMTP_USERNAME
		printf 'SMTP password: '
		read -r SMTP_PASSWORD
		;;
	esac
fi

# ── generate every secret ───────────────────────────────────────────
gen_hex()  { openssl rand -hex "$1"; }
gen_pass() { openssl rand -base64 18 | tr '+/' '-_' | tr -d '\n='; }

POSTGRES_PASSWORD="$(gen_hex 16)"
JWT_SECRET="$(gen_hex 48)"
SUPERADMIN_PASSWORD="$(gen_pass)"

# ── write .env ──────────────────────────────────────────────────────
if [ -f "$ENV_FILE" ] && [ "${FORCE:-}" != "1" ]; then
	die "$ENV_FILE already exists — move it aside or rerun with FORCE=1"
fi

cat >"$ENV_FILE" <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%MZ) — safe to edit, then restart.
ADDA_DOMAIN=$ADDA_DOMAIN

POSTGRES_USER=adda
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=adda

JWT_SECRET=$JWT_SECRET
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=10080

SUPERADMIN_USERNAME=admin
SUPERADMIN_EMAIL=$SUPERADMIN_EMAIL
SUPERADMIN_PASSWORD=$SUPERADMIN_PASSWORD
SEED_TEST_USERS=false

CORS_ORIGINS=https://$ADDA_DOMAIN
HLS_BASE_URL=https://$ADDA_DOMAIN/hls
NEXT_PUBLIC_API_BASE_URL=https://$ADDA_DOMAIN
NEXT_PUBLIC_HLS_BASE_URL=https://$ADDA_DOMAIN/hls
PASSWORD_RESET_URL=https://$ADDA_DOMAIN/reset-password

SMTP_HOST=$SMTP_HOST
SMTP_PORT=${SMTP_PORT:-587}
SMTP_USERNAME=${SMTP_USERNAME:-}
SMTP_PASSWORD=${SMTP_PASSWORD:-}
SMTP_FROM=adda <noreply@$ADDA_DOMAIN>
SMTP_STARTTLS=true
EOF
chmod 600 "$ENV_FILE"

# ── build & start ───────────────────────────────────────────────────
say "Building images (first run takes a few minutes)…"
cd "$REPO_DIR"
docker compose --profile prod up -d --build

say "Waiting for the backend to become healthy…"
i=0
while [ $i -lt 60 ]; do
	health="$(docker compose ps --format '{{.Health}}' backend 2>/dev/null || true)"
	[ "$health" = "healthy" ] && break
	i=$((i + 1))
	sleep 5
done
[ "$health" = "healthy" ] || die "backend did not become healthy — check: docker compose logs backend"

# ── done ────────────────────────────────────────────────────────────
say "──────────────────────────────────────────────"
say "adda is live:  https://$ADDA_DOMAIN"
say ""
say "  admin login:  $SUPERADMIN_EMAIL"
say "  password:     $SUPERADMIN_PASSWORD"
say ""
say "  Change this password after first sign-in (Settings)."
say "  It is stored only in .env — this is the only time it is shown."
say ""
say "  OBS stream URL:  rtmp://$ADDA_DOMAIN/live"
say "  Stream keys:     create a channel, then channel settings"
say "──────────────────────────────────────────────"
